### ISSUE TITLE
Issues using .on(...)

### ISSUE THREAD

**Issue by jrdmcgr** [cowboy/jquery-resize#10]
Is there anyway to bind to elements added after the handler is called?

Using `$('body').on('resize', '#selector', myFunction)` doesn't seem to work at all. 

Using `$('#selector').resize(myFunction)` works, but it doesn't bind to elements that are added by ajax.

**Comment by cowboy** [comment]
Because browsers don't actually trigger resize events, the jQuery event has to be bound specifically to each element you want to monitor. Event delegation won't work.

**Comment by jrdmcgr** [comment]
Thanks for the explanation. Do you know of any way to work around this issue? I see that the plugin is polling for changes. Would rebinding in this loop be expensive?

**Comment by cowboy** [comment]
I don't know of any way to work around this issue.

**Comment by krnlde** [comment]
I've seen some plugins polling every ~50ms and triggering the resize. It's not expensive if you use it carefully, but not on every element on your page.
