### ISSUE TITLE
resize and ui tabs

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [cowboy/jquery-resize#7]
I've noticed jquery ui tabs triggers the resize event when you switch to a tab.

Simple example:
http://jsfiddle.net/KF6Ka/1/

Is this a bug related to the plugin somehow?

**Comment by dmak** [comment]
And I observe the strange behaviour as well: UI tabs don't issue resize event at all (neither `$('.ui-tabs').resize(...)` nor `$('.ui-tabs-nav').resize(...)`).

**Comment by FagnerMartinsBrack** [comment]
Wow, this one is old. I can't reproduce the problem though, and I don't even recall why I opened this in the first place.

**Comment by dmak** [comment]
Hm, indeed. I [tried it again](http://jsfiddle.net/u3dffhes/2/) and it works fine. Sorry for false alarm.

**Comment by FagnerMartinsBrack** [comment]
I am closing then.
